"""profilo fisiologico e zone FC

Revision ID: 4598c0356064
Revises: 834228f97a0e
Create Date: 2026-08-14 18:00:08.466166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4598c0356064'
down_revision: Union[str, None] = '834228f97a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hr_zones_json', sa.JSON(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hr_max', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hr_rest', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lthr', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ftp', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ftp')
        batch_op.drop_column('lthr')
        batch_op.drop_column('hr_rest')
        batch_op.drop_column('hr_max')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('sex')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('hr_zones_json')

    # ### end Alembic commands ###
