"""schema v2 multiutente

Revision ID: 5aa9a58056d7
Revises: 
Create Date: 2026-08-14 02:04:15.541497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa9a58056d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garmin_email', sa.String(), nullable=False),
    sa.Column('garmin_password_encrypted', sa.String(), nullable=False),
    sa.Column('garmin_password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('ai_quota_chat_daily', sa.Integer(), nullable=False),
    sa.Column('ai_quota_plans_monthly', sa.Integer(), nullable=False),
    sa.Column('notify_prefs_json', sa.JSON(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('sync_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_garmin_email'), ['garmin_email'], unique=True)

    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('garmin_activity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Float(), nullable=True),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('avg_cadence', sa.Float(), nullable=True),
    sa.Column('avg_power', sa.Float(), nullable=True),
    sa.Column('aerobic_te', sa.Float(), nullable=True),
    sa.Column('anaerobic_te', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'garmin_activity_id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_garmin_activity_id'), ['garmin_activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_user_id'), ['user_id'], unique=False)

    op.create_table('ai_usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_log_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_log_user_id'), ['user_id'], unique=False)

    op.create_table('body_composition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('weight_g', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('body_water_pct', sa.Float(), nullable=True),
    sa.Column('muscle_mass_g', sa.Float(), nullable=True),
    sa.Column('bone_mass_g', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day')
    )
    with op.batch_alter_table('body_composition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_composition_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_composition_user_id'), ['user_id'], unique=False)

    op.create_table('chat_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('daily_coach_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('readiness_label', sa.String(), nullable=True),
    sa.Column('coach_message', sa.Text(), nullable=True),
    sa.Column('workout_json', sa.JSON(), nullable=True),
    sa.Column('insights_json', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day')
    )
    with op.batch_alter_table('daily_coach_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_coach_cache_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_coach_cache_user_id'), ['user_id'], unique=False)

    op.create_table('daily_wellness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('step_goal', sa.Integer(), nullable=True),
    sa.Column('total_distance_m', sa.Float(), nullable=True),
    sa.Column('floors_up', sa.Float(), nullable=True),
    sa.Column('floors_goal', sa.Float(), nullable=True),
    sa.Column('resting_hr', sa.Float(), nullable=True),
    sa.Column('min_hr', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Float(), nullable=True),
    sa.Column('avg_stress', sa.Float(), nullable=True),
    sa.Column('max_stress', sa.Float(), nullable=True),
    sa.Column('body_battery_high', sa.Float(), nullable=True),
    sa.Column('body_battery_low', sa.Float(), nullable=True),
    sa.Column('avg_spo2', sa.Float(), nullable=True),
    sa.Column('avg_respiration', sa.Float(), nullable=True),
    sa.Column('moderate_intensity_min', sa.Float(), nullable=True),
    sa.Column('vigorous_intensity_min', sa.Float(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('active_calories', sa.Float(), nullable=True),
    sa.Column('bmr_calories', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day')
    )
    with op.batch_alter_table('daily_wellness', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_wellness_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_wellness_user_id'), ['user_id'], unique=False)

    op.create_table('gamification_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.String(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('badges_json', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gamification_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gamification_state_user_id'), ['user_id'], unique=True)

    op.create_table('invite_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('used_by_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['used_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_codes_code'), ['code'], unique=True)

    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_log_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_log_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_log_user_id'), ['user_id'], unique=False)

    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'endpoint')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('sleep_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('total_sleep_sec', sa.Float(), nullable=True),
    sa.Column('deep_sleep_sec', sa.Float(), nullable=True),
    sa.Column('light_sleep_sec', sa.Float(), nullable=True),
    sa.Column('rem_sleep_sec', sa.Float(), nullable=True),
    sa.Column('awake_sec', sa.Float(), nullable=True),
    sa.Column('sleep_score', sa.Float(), nullable=True),
    sa.Column('resting_hr', sa.Float(), nullable=True),
    sa.Column('avg_spo2', sa.Float(), nullable=True),
    sa.Column('avg_respiration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day')
    )
    with op.batch_alter_table('sleep_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sleep_records_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_sleep_records_user_id'), ['user_id'], unique=False)

    op.create_table('training_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('vo2max', sa.Float(), nullable=True),
    sa.Column('vo2max_cycling', sa.Float(), nullable=True),
    sa.Column('training_status', sa.String(), nullable=True),
    sa.Column('training_load', sa.Float(), nullable=True),
    sa.Column('hrv_weekly_avg', sa.Float(), nullable=True),
    sa.Column('hrv_status', sa.String(), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('readiness_level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day')
    )
    with op.batch_alter_table('training_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_metrics_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_metrics_user_id'), ['user_id'], unique=False)

    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('priority_notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_goals_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_goals_user_id'), ['user_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tools_used_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('training_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('plan_json', sa.JSON(), nullable=False),
    sa.Column('weeks_total', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['user_goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_plans_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_plans_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_training_plans_active'))

    op.drop_table('training_plans')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_conversation_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_goals_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_goals_active'))

    op.drop_table('user_goals')
    with op.batch_alter_table('training_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_metrics_user_id'))
        batch_op.drop_index(batch_op.f('ix_training_metrics_day'))

    op.drop_table('training_metrics')
    with op.batch_alter_table('sleep_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sleep_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_sleep_records_day'))

    op.drop_table('sleep_records')
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_user_id'))

    op.drop_table('push_subscriptions')
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_log_sent_at'))
        batch_op.drop_index(batch_op.f('ix_notification_log_event_type'))

    op.drop_table('notification_log')
    with op.batch_alter_table('invite_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_codes_code'))

    op.drop_table('invite_codes')
    with op.batch_alter_table('gamification_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gamification_state_user_id'))

    op.drop_table('gamification_state')
    with op.batch_alter_table('daily_wellness', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_wellness_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_wellness_day'))

    op.drop_table('daily_wellness')
    with op.batch_alter_table('daily_coach_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_coach_cache_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_coach_cache_day'))

    op.drop_table('daily_coach_cache')
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_conversations_user_id'))

    op.drop_table('chat_conversations')
    with op.batch_alter_table('body_composition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_composition_user_id'))
        batch_op.drop_index(batch_op.f('ix_body_composition_day'))

    op.drop_table('body_composition')
    with op.batch_alter_table('ai_usage_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_log_day'))

    op.drop_table('ai_usage_log')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_user_id'))
        batch_op.drop_index(batch_op.f('ix_activities_start_time'))
        batch_op.drop_index(batch_op.f('ix_activities_garmin_activity_id'))

    op.drop_table('activities')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_garmin_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
